version: '3.4'

networks:
  workshopapp:

services:
  workshopdb:
    container_name: workshop-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    #volumes:
      #- /var/opr/mssql/data/WorkshoDb.mdf
    ports:
      - 8002:1433
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    networks:
      - workshopapp
  workshopweb:
    container_name: workshop-web
    image: ${DOCKER_REGISTRY-}workshopweb
    build:
      context: .
      dockerfile: WorkshopWeb/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - workshopdb
    environment:
      - DB_HOST=workshop-db
      - DB_NAME=WorkshopDb
      - DB_SA_PASSWORD=Password123
    networks:
      - workshopapp